spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/searchengine?createDatabaseIfNotExist=true
    username: root
    password: AdgjMptw123
    hikari:
      maximum-pool-size: 500
      connection-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        use-new-id-generator-mappings: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
        default-character-set: utf8mb4
        enable_lazy_load_no_trans: true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: info
configs:
  userAgent: SearchBot
  webInterfacePath: /admin
  sites:
    -
      url: http://www.playback.ru
      name: Playback
    -
      url: https://ipfran.ru
      name: ИПФ РАН
